### ISSUE TITLE
Twitter File Format Additional Information

### ISSUE THREAD

**Issue by MurageKibicho** [MarginaliaSearch/MarginaliaSearch#107]
Hello. 
I responded to your [tweet](https://x.com/MarginaliaNu/status/1814370557372084282) where you ask for help with a file format. Perhaps you could **generate a sample dataset for my perusal** or **point me towards the code that generates your data**. 

Clearly, you understand the dataset's distribution - (not to get too deep into the weeds, but they're constructed by bitwise-concatenating different non-unique id:s to form a unique id, leading to a statistical distribution of differences that is tri-modal)

Here are the file formats I hope tp explore 
1. LZ4 - super fast encoding and decoding. Requires 5 lines of code to get started.
2. Zstd - permits training a custom dictionary.
3. Custom binary arithmetic coder - We know the distribution so we can write a fast arithmetic coder for ourselves.

**Comment by vlofgren** [comment]
Hi, if you're interested in experimenting with compressing the data, I exported a sample.  I have a codec that compresses this data at about 80% compared to just storing them uncompressed in 64 bit longs, it's based around the Elias Gamma and Delta codes.  The code for this is in a bit of a jumble and not very well documented as it's currently being worked on, but you're welcome to look at the problem if you want.  Here's the [reader](https://github.com/MarginaliaSearch/MarginaliaSearch/blob/2bb9f18411925c1b915b3c6a0257df8d2f59f7d1/code/index/index-reverse/java/nu/marginalia/index/PrioIndexEntrySource.java#L76)  for the current compression algorithm to give you some clue of what I've come up with

Below is a small 100MB sample of the data.  Note I've just printed the numbers in a text file, to make them to load and work with and not have to deal with endianess and other non-portable matters of binary representation.  Each sample is separated by a string that begins with a #-sign. 

https://www.marginalia.nu/junk/testdata.txt.gz

The data itself is a 64 bit value that consists of three fields.  The  lowest 26 bits is a document ordinal, the following 31 bits is a domain ID, the next 6 bits are a ranking component used to alter the sort order (the sign bit is never set)
