### ISSUE TITLE
brainbaking.com site preview links to git.brainbaking.com

### ISSUE THREAD

**Issue by vlofgren** [MarginaliaSearch/MarginaliaSearch#108]
In https://search.marginalia.nu/site/brainbaking.com, the website link and preview URLs are all for git.brainbaking.com.  This seems decidedly off.   Additionally several of the documents have broken summaries with goatcounter HTML.

**Comment by vlofgren** [comment]
My hunch is we're pulling results by doing a site:domainname.com search, which will include results for all subdomains.  If so we should probably add a domain-id limit as well to restrict to results only from the indicated domain.

**Comment by vlofgren** [comment]
First part was as easy as that, fixed and deployed f19148132afb6a4fc734d18fa12c1c77d5d42294

Second part will require more work.  Clearly something is up with the summarizer.

**Comment by wgroeneveld** [comment]
Thanks again for looking into this, if there's anything I can provide or do to help let me know!

**Comment by vlofgren** [comment]
Should be pretty easy to reproduce when there's a known document that causes problems with the summary logic.  

Though if you find any additional jank, do let me know :)

**Comment by vlofgren** [comment]
Fixed as part of PR #99 via dc67c81f9982dfa03deecd1a8e830a6183a65392, will close the issue when that PR goes live.
