### ISSUE TITLE
No results on a site-specific search for a known phrase

### ISSUE THREAD

**Issue by shedivesin** [MarginaliaSearch/MarginaliaSearch#112]
This is, I'm sure, a pretty bizarre use-case of your lovely search engine, but I found what appears to me to be a bug. It is really not important, but on the off chance it provides you with a test case for something that is, here it is. Thanks!

---

I happen to know that Socrates is fond of swearing oaths by Anubis (...yes, I'm weird), and wanted to quickly hunt up all the times he does so. My favorite site for the classics is sacred-texts.com, so I searched for `site:sacred-texts.com/cla/plato/ "by the dog"`, which I know should turn up a bunch of hits (in the Republic, the Apology, the Phaedo, the Gorgias...). However, <a href="https://search.marginalia.nu/search?query=site%3Asacred-texts.com%2Fcla%2Fplato%2F+%22by+the+dog%22">I got nothing back</a>.

I tried several variations on this, like `site:sacred-texts.com "by the dog"` or `site:sacred-texts.com/cla/plato/ dog`, but didn't get anything, either. I was going to assume all the texts of Plato at this domain simply aren't indexed, but <a href="https://search.marginalia.nu/search?query=site%3Asacred-texts.com+socrates">a search for `site:sacred-texts.com socrates`</a> turns up hits from Plato (though I have to scroll a bit to find them). Curiously, <a href="site:sacred-texts.com/cla/plato/ socrates">a search for `site:sacred-texts.com/cla/plato/ socrates`</a> does not. (Am I misusing the `site:` keyword to search by a URL prefix and not just a domain name?)

For comparison, <a href="https://www.google.com/search?q=site%3Asacred-texts.com%2Fcla%2Fplato%2F+%22by+the+dog%22">Google gives back a reasonable result</a>, and <a href="https://duckduckgo.com/?q=site%3Asacred-texts.com%2Fcla%2Fplato%2F+%22by+the+dog%22">DuckDuckGo gives a couple results</a> (but not all of them).

**Comment by vlofgren** [comment]
Thanks for filing the issue.   

Phrase searching is a bit broken in the version that is currently running in production, really only works in a few cases.  I'm currently working on an overhaul of this #99, it should hopefully be up within a month or so and will permit full phrase matching capabilities as you'd expect them to work :-)

**Comment by shedivesin** [comment]
Sounds great---I'll pay attention to when that goes out and give this a try again then. Thank you!

**Comment by vlofgren** [comment]
Should be supported now.  I can't find the passages on sacred-texts (maybe it's not fully indexed? hmm), though I had success with classics.mit.edu: 

https://search.marginalia.nu/search?query=%22by+the+dog%22+site%3Aclassics.mit.edu&js=default&adtech=default&searchTitle=default&profile=corpo&recent=default

**Comment by shedivesin** [comment]
I think phrase searching works! As you note, I didn't see anything when I repeated my "by the dog" search, but searching for some other phrase that I knew existed in a page that I knew was indexed worked OK.

Digging in, I think there's a couple other issues, though.

First, there's an issue with the `site:` search option when given a URL prefix.

* `site:sacred-texts.com/cla/plato/ socrates` turns up nothing at all.
* `site:sacred-texts.com socrates` gives results (including results like `https://sacred-texts.com/cla/plato/timaeus.htm`).

Second, I think `sacred-texts.com` is simply incompletely indexed. For example, if I do a site-wide search for Plato, I see a few of Plato's dialogues pop up (like the Timaeus and the Critias), but I don't see others, and the phrase "by the dog" doesn't, in fact, turn up in the pages I see indexed.

I'm not sure what can be done about the second of these, but would you like me to file an Issue for the first?
