### ISSUE TITLE
RSS feed for publicity column

### ISSUE THREAD

**Issue by Jon-guy30** [MarginaliaSearch/MarginaliaSearch#38]
Hi! instead of sending another email I thought I'd post to GitHub this time. 
I'd like an RSS feed for the "Publicity, Discussion and Events" column on marginalia. I'm already following the maintenance logs, I'd like to be able to follow what the press is saying about marginalia. There haven't been any news lately but when there is an update, why not make it an RSS feed too? Unless I missed it somehow, I'm not seeing a feed for it.

**Comment by vlofgren** [comment]
Done, should be in production in a few days.  

https://github.com/MarginaliaSearch/MarginaliaSearch/commit/93f49f1fb3109c2e0d5f427cd2494eaa97e80f04
