### ISSUE TITLE
Improve list of indexed sites

### ISSUE THREAD

**Issue by comsomisha** [MarginaliaSearch/MarginaliaSearch#4]
Your search engine is very unique. But i have some ideas for improving the list of indexed sites.
1) Below is a short useful list of sites dedicated to the analysis of search engines in the English-speaking space.
seirdy.one + Webmentions
thenewleafjournal.com
dkb.io
dkb.blog (new version of dkb.io)
Website dkb.io is not indexed, although there are many mentions of this site on the news.ycombinator.com. Webmentions (best sample on site dkb.io) will help expand the search for sites that have not been indexed.
2) What about aggregators of useful links in the Spanish-speaking space?

**Comment by vlofgren** [comment]
Could you elaborate how webmentions would help? I don't quite follow.

Regarding 2), currently English is the only language that is supported. Supporting other languages would require a fairly significant development effort (to do it well), the biggest bottleneck is probably that I need someone who is both fluent in that language and relatively familiar with the guts of the code base. It's something I want to do down the line, but it's probably quite some while away.

**Comment by comsomisha** [comment]
1) I will try to show by example:
https://seirdy.one/posts/2021/03/10/search-engines-with-own-indexes/
96 web mentions are gathered at the bottom of the page. In the simplest case, you can add them to the index. Although their use may be the most incredible.
2) Just in case, I will clarify useful links on the topic of search engine analysis. It can be noticed that the Spanish-speaking space is not covered at all.
https://seirdy.one/posts/2021/03/10/search-engines-with-own-indexes/
https://thenewleafjournal.com/a-2021-list-of-alternative-search-engines-and-search-resources/
https://dkb.blog/p/google-search-is-dying
https://dkb.blog/p/the-next-google

**Comment by vlofgren** [comment]
I think the crawler should actually pick up these webmentions automagically. 

I've added Dmitri's new blog address to the crawl queue, should crop up in the next crawl batch.
