### ISSUE TITLE
Overflow text in search results cards title

### ISSUE THREAD

**Issue by canteuni** [MarginaliaSearch/MarginaliaSearch#43]
Hi !

I was playing a bit with the search engine when I encounter this bug when displaying a search result. I guess a picture says more than thousands words : 
![Screenshot 2023-08-31 at 10-24-02 Marginalia Search - BMC ipmi error](https://github.com/MarginaliaSearch/MarginaliaSearch/assets/21243338/41e746e6-e1f2-42eb-a113-3fc53aa33d01)

Hope that helps.
Congratulation for the search engine, this project seems really cool !

**Comment by vlofgren** [comment]
Fixed https://github.com/MarginaliaSearch/MarginaliaSearch/commit/e23976f6c4b781f99f368b3dd0d25a8a27d74040
