### ISSUE TITLE
Wrong content-type for opensearchdescription

### ISSUE THREAD

**Issue by JulienPalard** [MarginaliaSearch/MarginaliaSearch#60]
Hi! I tried to add Marginalia to my Firefox but right clicking the urlbar don't give me the expected "Add Marginalia Search" thing.

I looked at it, and according to https://developer.mozilla.org/en-US/docs/Web/OpenSearch#troubleshooting_tips the xml document should be provided with a `application/opensearchdescription+xml` content type, but it is not:

```
$ curl -I https://search.marginalia.nu/opensearch.xml
HTTP/1.1 200 OK
Server: nginx/1.22.1
Date: Fri, 10 Nov 2023 07:59:16 GMT
Content-Type: text/html;charset=utf-8
```

I don't know if fixing the content type is enough, but it'll probably be a good first step :)

**Comment by vlofgren** [comment]
Hmm, strange.  Works when I try with a clean Firefox LTS.  I'll see about implementing the changes, off on a branch working on front-end stuff now so it'll be a few days.

**Comment by vlofgren** [comment]
Fixed now.
