### ISSUE TITLE
Dark Theme on search.marginalia.nu

### ISSUE THREAD

**Issue by samstorment** [MarginaliaSearch/MarginaliaSearch#68]
# Overview

https://search.marginalia.nu no longer has dark mode styles. 

I tested on a couple browsers on a couple devices and made sure dark mode was enabled at the OS level but the search page stays on a light theme. I'd love for dark mode to return; perhaps it was removed by accident.

## Additional Info

It's been quite a bit of time since I first noticed dark theme was missing, maybe a month or more. I'm only just getting around to making an issue.

Dark mode appears to work on other pages (at least https://www.marginalia.nu) when I toggle my color preferences at the OS level.

Could maybe be its own issue, but the first time I noticed dark theme was missing I also noticed that the search page is quite a bit narrower. It seems like it used to span the full page width or quite close to it. I was a fan of the wider search page, although I suppose this comes down to personal preference.

**Comment by vlofgren** [comment]
Yeah I temporarily axed the dark mode when redesigning the search page.  Plan is to bring it back sometime, but I felt like I had my fill of CSS for the moment so it's a website for those with sunglasses for a while ;-)   I hope to bring it back though.

Thanks for the feedback.

**Comment by rooiratel** [comment]
Seems like this can be closed now.

**Comment by samstorment** [comment]
Closed by #94
