### ISSUE TITLE
Page returned after report shows raw HTML instead of rendered HTML

### ISSUE THREAD

**Issue by danluu** [MarginaliaSearch/MarginaliaSearch#72]
I reported a website that's some kind of spam website that's a clone of another website. After reporting it, I was forwarded to a page that showed me the raw HTML that's intended to be rendered rather than rendered page. Screenshot attached attached below:

![website-clone](https://github.com/MarginaliaSearch/MarginaliaSearch/assets/157136/7dbc53e4-80b8-4612-8740-9d3c745adaa9)

This was on Firefox 121.0 on a Mac. I did not attempt to reproduce this because I don't know how I'd be able to reproduce this without filing reports which would either be duplicates or false.

**Comment by vlofgren** [comment]
Should be resolved now with https://github.com/MarginaliaSearch/MarginaliaSearch/commit/97e11e1ac9b5cf6d76a1da9501a7745792bb398c
