### ISSUE TITLE
Bang Commands

### ISSUE THREAD

**Issue by conor-f** [MarginaliaSearch/MarginaliaSearch#76]
I've been enjoying using Marginalia, but as it has a higher rate of serendipity, it can make it difficult when you're not exploring a topic, but looking for some very precise content in my experience.

Would adding support for ["bang commands"](https://duckduckgo.com/bangs) be something that would fit within the project's goals/objectives? Allowing you to optionally search on a different engine for specific queries?

Not sure if this is already supported/this is the correct venue to discuss this, but let me know and I am happy to move the conversation elsewhere!

**Comment by vlofgren** [comment]
Marginalia's actually had this, but it's apparently broken at some point.  Fixed it now.  Don't currently support all too many bangs, but google and ddg is in place, as well as a wikipedia shortcut that's just a shorthand for a marginalia query for wikipedia results as wikipedia's search isn't fantastic.

f2b39ad055aba5ec1d74056e189636a631b930e8

**Comment by conor-f** [comment]
Amazing thanks so much for that!
