### ISSUE TITLE
Why is search page aligned to the left?

### ISSUE THREAD

**Issue by Jon-guy30** [MarginaliaSearch/MarginaliaSearch#82]
If you go to https://www.marginalia.nu/ everything's centered. If you go to https://search.marginalia.nu/ and also the actual search result page everything's aligned to the left. Why? What happened? Stuff used to be somewhat centered before, like I remember the news column being almost to the right. I think this just looks bad.

**Comment by Jon-guy30** [comment]
To show you what I mean it according to archive.org it changed somewhere between December the 4th and December the 7th 2023. 

This is what the old site looked like: https://web.archive.org/web/20231204051331/https://search.marginalia.nu/ In my opinion much better than the current one.

I'd appreciate (in my opinion) a saner, more centered layout. Thanks!

**Comment by vlofgren** [comment]
Fixed, will show up in prod soon.
