### ISSUE TITLE
Setup and Install Issues

### ISSUE THREAD

**Issue by samstorment** [MarginaliaSearch/MarginaliaSearch#91]
## Setup and Install Issues

I cloned the latest version of the repo and I'm running into some issues when running `docker-compose up -d` in step 4 of the [run README](https://github.com/MarginaliaSearch/MarginaliaSearch/blob/master/run/readme.md). 

I get the following error messages when I pick option 3 for the full marginalia search instance in the previous `run/install.sh <directory>` step and then go run `docker-compose up`. This seems like it could be related to [this commit](https://github.com/MarginaliaSearch/MarginaliaSearch/commit/2a03014652f2fde286ee08441ca90fe934519c8a) that addresses some issues with zookeeper in a docker compose file.

```bash
$ docker-compose up
service "executor-service-2" depends on undefined service zookeeper: invalid compose project
```

I successfully used option 3 a few months ago to toy around with the project. After running into this issue, I watched [your setup video](https://www.youtube.com/watch?v=PNwMkenQQ24) and saw you picked the second option using the 2 node barebones instance and that works as expected!

I also tried the option 1 barebones instance after messing around with the other 2 for a while and I had some issues there as well. Maybe it's some nonsense related to WSL on Windows? (windows user, yuck). Here's that output:

```bash
$ docker-compose up
[+] Running 1/4
 ⠿ Network marginalia_wmsa  Created                                                                    0.0s
 ⠋ Container traefik        Creating                                                                   0.0s
 ⠋ Container mariadb        Creating                                                                   0.0s
 ⠋ Container zookeeper      Creating                                                                   0.0s
Error response from daemon: failed to mount local volume: mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/e4f8bee746172ccc1e7ed3a2aa4ee9d60a7fe92bd3950a0ea77ec75b7581a388:/var/lib/docker/volumes/marginalia_db/_data, flags: 0x1000: no such file or directory
```

## Docs Issue

I also noticed the [run README](https://github.com/MarginaliaSearch/MarginaliaSearch/blob/master/run/readme.md) lists Java 21 while the [Software Requirements on the Docs site](https://docs.marginalia.nu/1_overview/02_software-reqs/) lists Java 22.

## Closing

sorry I don't really know what the hell is going on when docker is involved, I just came here to tinker with some CSS :)

**Comment by vlofgren** [comment]
First issue was my fault, the template for the docker compose file wasn't set up properly.  Should work now.  As for your other issues, it's hard to give a good diagnosis, but it might be you have some old volume registered in docker that's causing issues.

If you aren't running anything else important with docker on the system, you might try something like 

(**WARNING** The second and third commands wipes most of your local docker setup **system-wide**)
```bash
docker compose down -v 
docker system prune -a
docker volume prune -a
```

**Comment by samstorment** [comment]
@vlofgren Yep I think it was related to volumes. I used the docker desktop app and just manually checked the marginalia related volumes and deleted them in mass and reran the setup steps and no longer had that issue.

Appreciate the help!

**Comment by vlofgren** [comment]
No worry. 

I'm actually doing a bit of front-endy stuff very soon myself, got a short laundry list of issues from an accessibility audit to deal with.  

I'll probably see if I can set up some sort of easier way of running the search GUI without bringing up the whole system, maybe like as a test or something.   It's kind of painful to work with as it is right now, feedback loop is far too long.

If you'd like to poke around in that area of the code, I can let you know when I get that working?

**Comment by samstorment** [comment]
Yeah absolutely that sounds great

**Comment by vlofgren** [comment]
Alright, I've merged my PR with accessibility change and it's now possible to start a mockup of the search service by running `./gradlew -i paperDoll`.  

It will take a moment to start, especially first time you run it. It's accessible on port 9999 after you see a line printed like "INFO: Started @21257ms".

It's currently not set up to mock every backend call, give me a holler if there's something in particular you want to look at, should be relatively easy to add more stuff.

**Comment by samstorment** [comment]
Nice that works! Two notable bits of UI that are missing that would be nice to have in the mocked UI are the front page news and the search suggestions as you type.

And just as an extra bit of info, I'm probably going to play around with exclusively front-end stuff since I know that decently well and have fun there. Any general overarching guidelines/suggestions/aesthetic opinions when it comes to front-end? These are my takeaways from being aware of the project for a while and spending a bit of time in the code, but please correct me or add more:

* Early internet vibe
* Accessibility conscious
* Text-based browser conscious (Maybe try to keep the DOM simple because of this? I've never used a text based browser.)
* Things should always work without JS, but it's ok to add some JS to improve things in key places

Maybe you've written about this type of stuff before and I just haven't seen it. Also sorry if I'm getting a bit too far out of scope for this GitHub issue

**Comment by vlofgren** [comment]
I updated the paperdoll to mock those aspects as well.  

I'm really not much of front-end guy myself, not for lack of ambitions just I'm not very good at it, so any improvements you can make would be appreciated.  There's a no doubt a lot of room for improvements here and there :P 

But I think maybe we should close this issue.  

If you have something just make a WIP PR and we can discuss the change in there.  Your understanding of what the project is about seems fairly accurate so it'll probably be fine.
